name: Run Cypress Tests

on:
  push:
    branches:
      - testing # Only runs on the "testing" branch
  pull_request:
    branches:
      - testing # Runs when a PR is made to "testing" branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Pulls the latest code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Ensure compatibility with Cypress

      - name: Install dependencies
        working-directory: next-app # Set the correct directory
        run: npm install # Installs all project dependencies

      - name: Start application server
        working-directory: next-app
        run: npm run dev & # Starts your app in the background

      - name: Wait for server to be ready
        working-directory: next-app
        run: npx wait-on http://localhost:3000 # Adjust if your app runs on a different port

      - name: Run Cypress tests
        working-directory: next-app
        run: npx cypress run # Runs Cypress in headless mode

      - name: Upload Cypress test artifacts (screenshots & videos on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: next-app/cypress/screenshots # Store artifacts inside "next-app"

      - name: Notify failure
        if: failure()
        run: echo "Cypress tests failed. Check artifacts for details."
